/**
 * Legacy SSE route. Insight generation and caching are owned by Admin now.
 * The current UI reads the cache through tRPC and does not call this endpoint.
 */

import { NextResponse } from 'next/server'

export async function POST() {
  return NextResponse.json(
    { error: 'AI insights are generated by RunPaceFlow Admin' },
    { status: 410 },
  )
}
